packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  '@turbo/gen': ^2.4.4
  '@types/node': ^22.13.9
  '@types/react': 19.0.10
  '@types/react-dom': 19.0.4
  eslint: ^9.22.0
  next: ^15.2.1
  prettier: ^3.5.3
  react: ^19.0.0
  react-dom: ^19.0.0
  turbo: ^2.4.4
  typescript: ^5.8.2
  typescript-eslint: ^8.26.0
